-- Device / MAC / UA harvest help. Safe on live + new (INSERT OR IGNORE + UPDATE).
INSERT OR IGNORE INTO tt_help_core(pkey,displayname,htext) values ('device','Device','Extension type only: General SIP, WebRTC, or MAILBOX. Handset brand/model come from SIP registration harvest (device vendor / device model), not this field. MAC address is optional inventory and does not set the type.');
INSERT OR IGNORE INTO tt_help_core(pkey,displayname,htext) values ('macaddr','MAC address','Optional desk inventory note (best effort). Not used to detect phone brand or model — that comes from the phone''s SIP User-Agent when it registers. Clear or edit anytime; uniqueness is for hygiene only.');
INSERT OR IGNORE INTO tt_help_core(pkey,displayname,htext) values ('devicevendor','Device vendor','Brand learned from the phone''s SIP User-Agent when it registers to this home (async harvest). Read-only. Shown with model as e.g. Yealink (T46U).');
INSERT OR IGNORE INTO tt_help_core(pkey,displayname,htext) values ('devicemodel','Device model','Model token learned from the SIP User-Agent (async harvest). Read-only. Shown with vendor as e.g. Yealink (T46U).');
INSERT OR IGNORE INTO tt_help_core(pkey,displayname,htext) values ('lastseen','Last seen','When harvest last observed this extension''s registered User-Agent (UTC). Stale after a handset swap until the new phone registers and the next harvest runs.');
INSERT OR IGNORE INTO tt_help_core(pkey,displayname,htext) values ('firstseen','First seen','When harvest first recorded a mapped User-Agent for this extension (UTC).');

UPDATE tt_help_core SET displayname='Device', htext='Extension type only: General SIP, WebRTC, or MAILBOX. Handset brand/model come from SIP registration harvest (device vendor / device model), not this field. MAC address is optional inventory and does not set the type.' WHERE pkey='device';
UPDATE tt_help_core SET displayname='MAC address', htext='Optional desk inventory note (best effort). Not used to detect phone brand or model — that comes from the phone''s SIP User-Agent when it registers. Clear or edit anytime; uniqueness is for hygiene only.' WHERE pkey='macaddr';
UPDATE tt_help_core SET displayname='Device vendor', htext='Brand learned from the phone''s SIP User-Agent when it registers to this home (async harvest). Read-only. Shown with model as e.g. Yealink (T46U).' WHERE pkey='devicevendor';
UPDATE tt_help_core SET displayname='Device model', htext='Model token learned from the SIP User-Agent (async harvest). Read-only. Shown with vendor as e.g. Yealink (T46U).' WHERE pkey='devicemodel';
UPDATE tt_help_core SET displayname='Last seen', htext='When harvest last observed this extension''s registered User-Agent (UTC). Stale after a handset swap until the new phone registers and the next harvest runs.' WHERE pkey='lastseen';
UPDATE tt_help_core SET displayname='First seen', htext='When harvest first recorded a mapped User-Agent for this extension (UTC).' WHERE pkey='firstseen';
