;
; This file is provided as part of the pbx3 Asterisk workbench pkg
; It is not a generated file so you may freely change it but it WILL be  
; overwritten if/when you upgrade pbx3 so please make a copy if you
; wish to preserve your changes across an upgrade
;
[pbx3_hosted_user]
type=user
music_on_hold_when_empty=yes  
music_on_hold_class=default   
announce_join_leave=yes 

[pbx3_user]
type=user
music_on_hold_when_empty=yes  
music_on_hold_class=default  
