;
;  Internal presets which are available system-wide
;
[internal-presets]
;
;	RCS Service Codes
;
;		
		exten => _*1[89][*],1,agi(gcsagi,${EXTEN},cfim,)	; DND ON/OFF
		exten => _*20[*],1,agi(gcsagi,${EXTEN},cfim,)		; DND TOGGLE

		exten => _*21*XX.,1,agi(gcsagi,${EXTEN},cfim,)		; cfim ON
		exten => _*21*,1,agi(gcsagi,${EXTEN},cfim,)		; cfim OFF

		exten => _*22*XX.,1,agi(gcsagi,${EXTEN},cfbs,)		; cfbs ON
		exten => _*22*,1,agi(gcsagi,${EXTEN},cfbs,)		; cfbs OFF		

		exten => _*23*,1,agi(gcsagi,${EXTEN},,)			; CF CLEAR

		exten => _*26[*],1,agi(gcsagi,${EXTEN},,)		; RingDelay
		exten => _*26[*]X,1,agi(gcsagi,${EXTEN},,)		; RingDelay
		exten => _*26[*]XX,1,agi(gcsagi,${EXTEN},,)	; RingDelay

        exten => *52*,1,PlayBack(demo-echotest)        		; Echotest
        exten => *52*,n,Echo
        exten => *52*,n,PlayBack(demo-echodone)
        exten => *55*,1,SayUnixTime(,,HMpABd)          		; SayTime/Date
        exten => *56*,1,PlayBack(vm-extension)
        exten => *56*,n,SayDigits(${CALLERID(num)})

;
;	ALL of these need to move into cluster contexts
;
        exten => _*60*XXXX,1,agi(gcsagi,${EXTEN},,)		; Greetings
        
        exten => _*6[34][*],1,agi(gcsagi,${EXTEN},,)		; Agent pause/unpause(63 64)
        exten => _*6[56][*],1,agi(gcsagi,${EXTEN},,)		; Agent Login/out(65 66)

        exten => _*67[*]XXXX,1,agi(gcsagi,${EXTEN},,)		; ChanSpy (Whisper)
        exten => _*67[*]XXX,1,agi(gcsagi,${EXTEN},,)		; ChanSpy (Whisper)        
        exten => _*68[*]XXXX,1,agi(gcsagi,${EXTEN},,)		; ChanSpy
        exten => _*68[*]XXX,1,agi(gcsagi,${EXTEN},,)		; ChanSpy
;
;
;


;
;	Wakeup call 
;	needs work for PJSIP and clusters



;
		exten => _*24[*],1,agi(kwakeup)
		exten => _*24[*]XXX,1,Authenticate(${SYSPASS})
		exten => _*24[*]XXX,n,agi(kwakeup,EXT${EXTEN:4})
		exten => _*24[*]XXXX,1,Authenticate(${SYSPASS})
		exten => _*24[*]XXXX,n,agi(kwakeup,EXT${EXTEN:4})
		exten => _***XXX,1,Set(CHANNEL(language)=${LANGUAGE})
		exten => _***XXX,n,Dial(PJSIP/${EXTEN:3},60)
		exten => _***XXXX,1,Set(CHANNEL(language)=${LANGUAGE})
		exten => _***XXXX,n,Dial(SIP/${EXTEN:3},60)

;
;	NANP Vertical Service Code Compatibility
;
       	exten => *60,1,GoTo(*55*,1) ; say time
       	exten => *65,1,GoTo(*56*,1) ; say extn num

       	exten => _*72X.,1,agi(gcsagi,*21*${EXTEN},,) 		;cfim ON
       	exten => *73,1,agi(gcsagi,*21*,,)					;cfim OFF

       	exten => _*77XXXX,1,agi(gcsagi,*60*${EXTEN},,)		;play a greeting;

       	exten => *78,1,agi(gcsagi,*18*,,)					;DND ON
       	exten => *79,1,agi(gcsagi,*19*,,)					;DND OFF

       	exten => _*90X.,1,agi(gcsagi,*22*${EXTEN},,)		;cfbs ON
       	exten => *91,1,agi(gcsagi,*22*,,)					;cfbs OFF

       	exten => *97,1,GoTo(*50*,1)								;DND ON
       	exten => *98,1,GoTo(*52*,1)								;DND OFF
       	exten => _*99XXXX,1,agi(gcsagi,*61*${EXTEN},,)
       	exten => i,1,Playtones(congestion)