#!/bin/bash

##
## ToDo replace original asterisk files
##

sv d sys-ua-responder
sv d sys-ua-helper

# nginx/API site cleanup is done by pbx3api package when it is removed

[ -L /etc/cron.d/pbx3 ] && rm -rf /etc/cron.d/pbx3

rm -rf /etc/service/sys*

[ -L /etc/fail2ban/jail.local ] && rm -f /etc/fail2ban/jail.local
[ -L /etc/fail2ban/action.d/shorewall.local ] && rm -f /etc/fail2ban/action.d/shorewall.local

# debsetlan (setip) is no longer a systemd service; installer runs setip directly
# systemctl disable debsetlan 2>/dev/null || true