;
; 	Withhold CLI for outbound SIP trunks
;   	This will work in most cases if the carrier is a good player
;
;   It will usually not work for IAX2 trunks and you'll need to figure out 
;	what your carrier requires
;   
;   In this default example, we use a prefix of 141 but you can change it to
;   whatever suits your usecase
;
[extensions_withhold_clid]		
        exten => _141XXXXX.,1,NoOp(withhold cli detected)
        exten => _141XXXXX.,n,Set(CALLERID(pres)=prohib)
        exten => _141XXXXX.,n,GoTo(\${EXTEN:3},1)
