;
; This file is provided as part of the GCS Asterisk workbench pkg
; It is not a generated file so you may freely change it but it WILL be  
; overwritten if/when you upgrade GCS so please make a copy if you
; wish to preserve your changes across an upgrade
;

[general]

enabled=yes
bindaddr=0.0.0.0
bindport=8088
tlsenable=yes
tlsbindaddr=0.0.0.0:8089
tlscertfile=/etc/ssl/certs/ssl-cert-snakeoil.pem
tlsprivatekey=/etc/ssl/private/ssl-cert-snakeoil.key
