;
; This file is provided as part of the GCS Asterisk workbench pkg
; It is not a generated file so you may freely change it but it WILL be  
; overwritten if/when you upgrade GCS so please make a copy if you
; wish to preserve your changes across an upgrade
;

[modules]
autoload=yes

noload => pbx_gtkconsole.so
noload => pbx_kdeconsole.so

noload => chan_sip.so
noload => chan_unistim
noload => res_config_ldap.so
noload => chan_mgcp.so
noload => chan_skinny.so
noload => res_phoneprov.so
noload => res_ari.so
noload => res_smdi.so
noload => res_ari_model.so
noload => res_hep_rtcp
noload => app_voicemail_imap.so
noload => app_voicemail_odbc.so

noload => chan_modem.so
noload => chan_modem_aopen.so
noload => chan_modem_bestdata.so
noload => chan_modem_i4l.so

noload => chan_capi.so

load => res_musiconhold.so

noload => chan_alsa.so
noload => chan_console.so
noload => chan_oss.so

noload => cdr_sqlite.so

noload => app_directory_odbc.so

noload => res_config_odbc.so
noload => res_config_pgsql.so
noload => res_pjsip_phoneprov_provider.so
noload => res_adsi
noload => res_adsi
noload => app_adsiprog
noload => res_monitor
noload => app_nbscat
noload => app_image
noload => app_ices
noload => app_mysql
noload => app_url
noload => cdr_mysql
noload => app_getcpeid

[global]
