;
; This file is provided as part of the GCS Asterisk workbench pkg
; It is not a generated file so you may freely change it but it WILL be  
; overwritten if/when you upgrade GCS so please make a copy if you
; wish to preserve your changes across an upgrade
;
 
#include pjsip_globals.conf
#include pjsip_transport.conf
#include pjsip_ready_trunks.conf
#include pjsip_anonymous.conf
#include pjsip_ready_phones.conf
#include pjsip_ready_webrtc.conf