;
; This file is provided as part of the GCS Asterisk workbench pkg
; It is not a generated file so you may freely change it but it WILL be  
; overwritten if/when you upgrade GCS so please make a copy if you
; wish to preserve your changes across an upgrade
;
[global]
type=global
user_agent=Asterisk PBX
default_realm = somewhere.com
keep_alive_interval=30
default_voicemail_extension=*50*
mwi_tps_queue_low=-1
debug=no
