;
; This file is provided as part of the PBX3 Asterisk workbench rpm
; It is not a generated file so you may freely change it but it WILL be  
; overwritten if/when you upgrade PBX3 so please make a copy if you
; wish to preserve your changes across an upgrade
;

[general]
format=wav
pbxskip=yes
serveremail=vm@PBX3
fromstring=PBX3 Voicemail
attach=yes
maxsecs=300
maxgreet=30
minsecs=2
maxsilence=6
operator=no
nextaftercmd=yes
externnotify=/opt/pbx3/scripts/vmnotify.sh
