#!/usr/bin/env bash
# Provision soak phones on golden catcher tenant (sipp / pb0wsk).
# Creates General SIP exts 2100–2139 (20 dialers + 20 answerers), GenAst Commit,
# writes soak-phones.env (gitignored) for run-soak.sh.
#
# Usage: ./provision-soak-phones.sh
# Requires: lab.env with GOLDEN_SSH + CATCHER_DOMAIN
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

if [[ ! -f lab.env ]]; then
  echo "Missing lab.env" >&2
  exit 1
fi
# shellcheck disable=SC1091
source ./lab.env

: "${GOLDEN_SSH:?Set GOLDEN_SSH in lab.env}"
: "${CATCHER_DOMAIN:?}"
CLUSTER_SU="${CATCHER_DOMAIN%%.*}"
OUT="${SOAK_PHONES_FILE:-$ROOT/soak-phones.env}"
DIALER_FIRST=2100
ANSWERER_FIRST=2120
COUNT=20

echo "Provisioning soak phones on ${CLUSTER_SU}: dialers ${DIALER_FIRST}+${COUNT}, answerers ${ANSWERER_FIRST}+${COUNT}"

# Upload provisioner
# shellcheck disable=SC2086
$GOLDEN_SSH "cat > /tmp/pbx3-provision-soak.php" <<'PHP'
<?php
declare(strict_types=1);

require '/opt/pbx3api/vendor/autoload.php';
$app = require '/opt/pbx3api/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Extension;
use Illuminate\Support\Facades\DB;

$cluster = getenv('CLUSTER_SU') ?: 'pb0wsk';
$dialerFirst = (int) (getenv('DIALER_FIRST') ?: 2100);
$answererFirst = (int) (getenv('ANSWERER_FIRST') ?: 2120);
$count = (int) (getenv('COUNT') ?: 20);

$device = DB::table('device')->where('pkey', 'General SIP')->first(['sipiaxfriend', 'technology']);
$pjsipuser = $device->sipiaxfriend ?? null;
$technology = $device->technology ?? 'SIP';

function ensure_phone(string $cluster, string $pkey, ?string $pjsipuser, string $technology): array
{
    $existing = Extension::query()->where('cluster', $cluster)->where('pkey', $pkey)->first();
    if ($existing) {
        $row = DB::table('ipphone')->where('id', $existing->id)->first(['shortuid', 'passwd']);
        return [(string) $row->shortuid, (string) ($row->passwd ?? ''), false];
    }

    $id = generate_ksuid();
    $shortuid = generate_shortuid();
    Extension::create([
        'id' => $id,
        'shortuid' => $shortuid,
        'pkey' => $pkey,
        'cluster' => $cluster,
        'dvrvmail' => $pkey,
        'desc' => 'Soak' . $pkey,
        'description' => 'SIPp L2 soak',
        'device' => 'General SIP',
        'transport' => 'udp',
        'protocol' => 'IPV4',
        'pjsipuser' => $pjsipuser,
        'technology' => $technology,
        'provisionwith' => 'IP',
        'active' => 'YES',
    ]);
    $pass = ret_password(12);
    Extension::where('id', $id)->update(['passwd' => $pass]);
    return [$shortuid, $pass, true];
}

function clone_cos(string $cluster, string $fromPkey, string $toPkey): void
{
    try {
        foreach (['ipphonecosopen', 'ipphonecosclosed'] as $table) {
            DB::table($table)->where('cluster', $cluster)->where('ipphone_pkey', $toPkey)->delete();
            $rows = DB::table($table)->where('cluster', $cluster)->where('ipphone_pkey', $fromPkey)->get();
            foreach ($rows as $row) {
                DB::table($table)->insert([
                    'ipphone_pkey' => $toPkey,
                    'cos_pkey' => $row->cos_pkey,
                    'cluster' => $cluster,
                ]);
            }
        }
    } catch (Throwable $e) {
        fwrite(STDERR, "cos clone warn {$toPkey}: " . $e->getMessage() . "\n");
    }
}

$created = 0;
$lines = [
    '# soak-phones.env — generated by provision-soak-phones.sh; do not commit',
    "SOAK_CLUSTER={$cluster}",
    "SOAK_DOMAIN={$cluster}.pbx3.com",
    "SOAK_PAIR_COUNT={$count}",
    "SOAK_DIALER_FIRST={$dialerFirst}",
    "SOAK_ANSWERER_FIRST={$answererFirst}",
];

for ($i = 0; $i < $count; $i++) {
    $dPkey = (string) ($dialerFirst + $i);
    $aPkey = (string) ($answererFirst + $i);
    [$dSu, $dPass, $dNew] = ensure_phone($cluster, $dPkey, $pjsipuser, $technology);
    [$aSu, $aPass, $aNew] = ensure_phone($cluster, $aPkey, $pjsipuser, $technology);
    if ($dNew) {
        clone_cos($cluster, '2000', $dPkey);
        $created++;
    }
    if ($aNew) {
        clone_cos($cluster, '2000', $aPkey);
        $created++;
    }
    $lines[] = "DIALER_{$i}_EXT={$dPkey}";
    $lines[] = "DIALER_{$i}_USER={$dSu}";
    $lines[] = "DIALER_{$i}_PASS={$dPass}";
    $lines[] = "ANSWERER_{$i}_EXT={$aPkey}";
    $lines[] = "ANSWERER_{$i}_USER={$aSu}";
    $lines[] = "ANSWERER_{$i}_PASS={$aPass}";
}

if ($created > 0) {
    set_commit_dirty();
}

fwrite(STDERR, "provision-soak: created={$created} pairs={$count}\n");
echo implode("\n", $lines) . "\n";
PHP

# shellcheck disable=SC2086
PHONES="$($GOLDEN_SSH "sudo CLUSTER_SU=$(printf %q "$CLUSTER_SU") DIALER_FIRST=$DIALER_FIRST ANSWERER_FIRST=$ANSWERER_FIRST COUNT=$COUNT php /tmp/pbx3-provision-soak.php")"

# Commit if anything new (idempotent GenAst is OK)
# shellcheck disable=SC2086
$GOLDEN_SSH bash -s <<'COMMIT'
set -euo pipefail
# SysCommand commit path used by SPA; fall back to genAst.sh
if [[ -x /opt/pbx3/scripts/genAst.sh ]]; then
  echo "Running GenAst Commit…"
  sudo /opt/pbx3/scripts/genAst.sh
else
  echo "WARN: genAst.sh missing — Commit from SPA" >&2
fi
COMMIT

{
  echo "# generated $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "$PHONES"
} >"$OUT"
chmod 600 "$OUT"
echo "Wrote $OUT"
echo "Next: rsync soak-phones.env to sippuac and ./run-soak.sh start demo"
