#!/bin/bash

##
## ToDo replace original asterisk files
##

sv d sys-ua-responder
sv d sys-ua-helper

rm -rf /etc/apache2/sites-enabled/pbx3*
rm -rf /etc/apache2/sites-available/pbx3*

[ -L /etc/cron.d/pbx3 ] && rm -rf /etc/cron.d/pbx3

rm -rf /etc/service/sys*

[ -L /etc/fail2ban/jail.local ] && rm -rf /etc/fail2ban/jail.local
[ -L /etc/fail2ban/action.d/shorewall.local ] && rm -rf /etc/fail2ban/action.d/shorewall.local
[ -L /etc/fail2ban/filter.d/asterisk.conf ] && /etc/fail2ban/filter.d/asterisk.conf 


systemctl disable  debsetlan