#!/bin/sh

. /opt/pbx3/scripts/bashconfig

[ ! -e $SIPLOG ] && mkdir $SIPLOG

FILES=$(sqlite3 $SYSDB "SELECT logsipnumfiles FROM globals LIMIT 1")
FILESIZE=$(sqlite3 $SYSDB "SELECT logsipfilesize FROM globals LIMIT 1")

exec 2>&1
exec /usr/bin/dumpcap -b filesize:$FILESIZE -b files:$FILES -f "port 5060" -w $SIPLOG/siplog.pcap > /dev/null 2>&1 