#!/bin/sh

. /opt/pbx3/scripts/bashconfig

[ ! -e $SIPLOG ] && mkdir $SIPLOG

FILES=$($SYSDB "SELECT LOGSIPNUMFILES from globals")
FILESIZE=$($SYSDB "SELECT LOGSIPFILESIZE from globals")

exec 2>&1
exec /usr/bin/dumpcap -b filesize:$FILESIZE -b files:$FILES -f "port 5060" -w $SIPLOG/siplog.pcap > /dev/null 2>&1 